
-- MySQL Script generated by MySQL Workbench
-- 05/29/19 23:19:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `truyum` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `truyum` ;

-- -----------------------------------------------------
-- Table `truyum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(60) NULL,
  `us_password` VARCHAR(60) NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `truyum`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`menu_item` (
  `me_id` INT NOT NULL AUTO_INCREMENT,
  `me_name` VARCHAR(100) NULL,
  `me_price` float(19,2) NULL,
  `me_active` BOOLEAN NULL,
  `me_date_of_launch` DATE NULL,
  `me_category` VARCHAR(45) NULL,
  `me_free_delivery` BOOLEAN NULL,
  `me_image` VARCHAR(100) NULL,
  PRIMARY KEY (`me_id`))
ENGINE = InnoDB;

ALTER TABLE menu_item modify me_image VARCHAR(300);
-- -----------------------------------------------------
-- Table `truyum`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`cart` (
  `ct_id` INT NOT NULL AUTO_INCREMENT,
  `ct_us_id` INT NULL,
  `ct_pr_id` INT NULL,
  PRIMARY KEY (`ct_id`),
  INDEX `ct_us_fk_idx` (`ct_us_id` ASC),
  INDEX `ct_pr_fk_idx` (`ct_pr_id` ASC),
  CONSTRAINT `ct_us_fk`
    FOREIGN KEY (`ct_us_id`)
    REFERENCES `truyum`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ct_pr_fk`
    FOREIGN KEY (`ct_pr_id`)
    REFERENCES `truyum`.`menu_item` (`me_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `truyum`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`role` (
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(60) NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `truyum`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `truyum`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_us_id` INT NULL,
  `ur_ro_id` INT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `ur_us_fk_idx` (`ur_us_id` ASC),
  INDEX `ur_ro_fk_idx` (`ur_ro_id` ASC),
  CONSTRAINT `ur_us_fk`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `truyum`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_ro_fk`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `truyum`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `truyum`.`menu_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `truyum`;
insert into  `truyum`.`menu_item`(me_name,me_price,me_active,me_date_of_launch,me_category,me_free_delivery,me_image)
 values("Burger", 129.00, true, '2017-12-23', "Main Course",
					false,'https://images.unsplash.com/photo-1512152272829-e3139592d56f?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=800');      
	
 insert into  `truyum`.`menu_item`(me_name,me_price,me_active,me_date_of_launch,me_category,me_free_delivery,me_image)
 values("Sandwich", 99.00, true,'2017-03-15', 
				"Main Course", true,'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1353&amp;q=80');
               
               
insert into  `truyum`.`menu_item`(me_name,me_price,me_active,me_date_of_launch,me_category,me_free_delivery,me_image)
 values( "Pizza", 149.00, true,'2018-08-21', "Main Course",
					false,'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1355&amp;q=80' ); 

insert into  `truyum`.`menu_item`(me_name,me_price,me_active,me_date_of_launch,me_category,me_free_delivery,me_image)
 values( "French Fries", 57.00, false,'2017-07-02',
					"Starters", true,'https://images.unsplash.com/photo-1526230427044-d092040d48dc?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1350&amp;q=80' );     
insert into  `truyum`.`menu_item`(me_name,me_price,me_active,me_date_of_launch,me_category,me_free_delivery,me_image)
 values( "Chocolate Brownie", 32.00, true,'2022-11-02',
					"Dessert", true,'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1330&amp;q=80' ); 
COMMIT;
-- -----------------------------------------------------
-- Data for table `truyum`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `truyum`;
INSERT INTO `truyum`.`user` (`us_id`,`us_name`,`us_password`) VALUES (1,'user','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK');
INSERT INTO `truyum`.`user` (`us_id`,`us_name`,`us_password`) VALUES (2,'admin','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK');
COMMIT;
-- -----------------------------------------------------
-- Data for table `truyum`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `truyum`;
INSERT INTO `truyum`.`role` (`ro_id`,`ro_name`) VALUES (1,'Admin');
INSERT INTO `truyum`.`role` (`ro_id`,`ro_name`) VALUES (2,'User');
COMMIT;
-- -----------------------------------------------------
-- Data for table `truyum`.`user_role`
-- -----------------------------------------------------
START TRANSACTION;
USE `truyum`;
INSERT INTO `truyum`.`user_role` (`ur_id`,`ur_us_id`,`ur_ro_id`) VALUES (1,1,2);
INSERT INTO `truyum`.`user_role` (`ur_id`,`ur_us_id`,`ur_ro_id`) VALUES (2,2,1);
INSERT INTO `truyum`.`user_role` (`ur_id`,`ur_us_id`,`ur_ro_id`) VALUES (4,1,1);

COMMIT;
-- -----------------------------------------------------
-- Data for table `truyum`.`cart`
-- -----------------------------------------------------
START TRANSACTION;
USE `truyum`;
INSERT INTO `truyum`.`cart` (`ct_id`,`ct_us_id`,`ct_pr_id`) VALUES (1,1,2);
INSERT INTO `truyum`.`cart` (`ct_id`,`ct_us_id`,`ct_pr_id`) VALUES (2,1,1);
INSERT INTO `truyum`.`cart` (`ct_id`,`ct_us_id`,`ct_pr_id`) VALUES (3,1,3);

COMMIT;
